platform :ios, :deployment_target => '6.1'

pod 'Reveal-iOS-SDK'
pod 'Firebase', '~> 1.1.7'
pod 'LXReorderableCollectionViewFlowLayout', :git => 'https://github.com/lxcid/LXReorderableCollectionViewFlowLayout.git'
pod 'Reachability'
